# Generated by Django 3.2.11 on 2022-03-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_kuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='managescholarship',
            name='srcYear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.academicyear', verbose_name='year'),
        ),
    ]
