# Generated by Django 3.2.11 on 2022-03-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_KUY2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerscholarship',
            old_name='nameScholarRegister',
            new_name='namescholarregister',
        ),
        migrations.RenameField(
            model_name='registerscholarship',
            old_name='regischo_id',
            new_name='register_id',
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='usermatch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user_login'),
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('studentinform_profile_stdfile', models.AutoField(primary_key=True, serialize=False)),
                ('filescholar_resume', models.FileField(blank=True, null=True, upload_to='file/')),
                ('stdinform_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.studentinform')),
                ('usermatch_id_stdfile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user_login')),
            ],
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='studentinform_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentfile'),
        ),
    ]
