# Generated by Django 3.2.11 on 2022-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kuy2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinform',
            name='available_ID',
            field=models.BooleanField(default=False),
        ),
    ]
