# Generated by Django 3.2.11 on 2022-03-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_kuy2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='stdinform_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentinform'),
        ),
    ]
