# Generated by Django 3.2.11 on 2022-03-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentfile_stdinform_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfile',
            name='filescholar_resume',
        ),
        migrations.CreateModel(
            name='StudentFileFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('file_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.studentfile')),
            ],
        ),
    ]
