# Generated by Django 3.2.11 on 2022-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_kuy2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='National_ID_card',
            field=models.FileField(blank=True, null=True, upload_to='ID_card/'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='Transcript',
            field=models.FileField(blank=True, null=True, upload_to='Transcript/'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='house_registration',
            field=models.FileField(blank=True, null=True, upload_to='house_registration/'),
        ),
        migrations.AddField(
            model_name='studentfilefile',
            name='fileTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='Profile_Essay',
            field=models.FileField(blank=True, null=True, upload_to='Profile_Essay/'),
        ),
    ]
