# Generated by Django 3.2.11 on 2022-03-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_kuy2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfile',
            old_name='national_ID_card',
            new_name='national_id_card',
        ),
        migrations.RenameField(
            model_name='studentfile',
            old_name='profile_Essay',
            new_name='profile_essay',
        ),
    ]
