# Generated by Django 3.2.11 on 2022-03-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_kuy2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerscholarship',
            old_name='status',
            new_name='statusCheck',
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='statusInterview',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='statusReceipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='statusTransfer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
