# Generated by Django 3.2.11 on 2022-03-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_kuy2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightcriteriapoint',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
