# Generated by Django 3.2.11 on 2022-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_kuy2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='Father_Profile_reg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='GPA_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='Mother_Profile_reg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='Other_Profile_reg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='Sibling_Profile_reg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='address_Std_reg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='advisor_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='available_ID_reg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='birthDate_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='email_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='fullName_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='id_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='image_Std_reg',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='major_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='phone_Std_reg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='term_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='year_Std_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
