# Generated by Django 3.2.11 on 2022-03-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_kuy2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commiteevote',
            fields=[
                ('commitee_id', models.AutoField(primary_key=True, serialize=False)),
                ('managescholarship_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.managescholarship')),
                ('registerscholarship_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.registerscholarship')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user_login')),
                ('weightcriteriapoint_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.weightcriteriapoint')),
            ],
        ),
    ]
