# Generated by Django 3.2.12 on 2022-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_point_weightcriteriapoint_weightpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='managescholarship',
            name='statusScholar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
