# Generated by Django 3.2.12 on 2022-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_managescholarship_statusscholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='managescholarship',
            name='processStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
