# Generated by Django 3.2.11 on 2022-04-04 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_studentfilefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfilefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'mp4'])]),
        ),
    ]
