# Generated by Django 3.2.11 on 2022-04-04 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_studentfilefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='house_registration',
            field=models.FileField(blank=True, null=True, upload_to='house_registration/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='national_id_card',
            field=models.FileField(blank=True, null=True, upload_to='ID_card/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='profile_essay',
            field=models.FileField(blank=True, null=True, upload_to='Profile_Essay/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='Transcript/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
