# Generated by Django 3.2.11 on 2022-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220404_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commiteevote',
            name='weightcriteriapoint_id',
        ),
        migrations.AddField(
            model_name='commiteevote',
            name='pointbycommitee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
