# Generated by Django 3.2.11 on 2022-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220405_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='managescholarship',
            name='normalOrcontinue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
