# Generated by Django 3.2.11 on 2022-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_managescholarship_normalorcontinue'),
    ]

    operations = [
        migrations.AddField(
            model_name='managescholarship',
            name='Round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registerscholarship',
            name='statusRound',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
