# Generated by Django 3.2.11 on 2022-04-06 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_kuy2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinform',
            name='image_Std',
            field=models.ImageField(blank=True, null=True, upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
