# Generated by Django 3.2.11 on 2022-04-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_kuy2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commiteevote',
            name='pointbycommitee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
