# Generated by Django 3.2.11 on 2022-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_kuy2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerscholarship',
            name='totalScore',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
