# Generated by Django 3.2.11 on 2022-04-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_kuy2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorialRegisterStudent',
        ),
    ]
